### PR TITLE
Add JPEG 2000 support with OpenJPEG

### PR DESCRIPTION
**Pull request by stweil**
This PR is similar to PR #61, but based on latest git master and with three new commits on top.

### CODE REVIEW

**Comment by boxerab** [comment]
:+1:

**Comment by boxerab** [comment]
@ruven do you think this PR is ready for merging, or is there more work that needs to be done?

**Comment by ruven** [comment]
It's good, but I see that there's still the unnecessary useOpenJPEG boolean. Remove this and I'll do the merge.

**Comment by stweil** [comment]
Done. All code and comments related to `useOpenJPEG` are removed now.

**Comment by boxerab** [comment]
@ruven how does the PR look to you now?  Also, once this gets merged, what is the best way of notifying users about the new feature ? IIIF Discuss google group ?

**Comment by ruven** [comment]
OK merged! Thanks for all your efforts with this!

**Pull request merged**
